import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="footer footer-center bg-base-300 p-4 text-2xl text-base-content">Deck.io</header>
        {children}

        <footer className="footer footer-center bg-base-300 p-4 text-base-content">
          <aside>
            <p>
              Copyright ©
              {new Date().getFullYear()}
              {' '}
              - All right reserved by ACME Industries Ltd
            </p>
          </aside>
        </footer>
      </body>
    </html>
  )
}
